# Generated by Django 2.2.2 on 2019-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dabang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const_date', models.CharField(max_length=100, verbose_name='준공년월')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('address', models.CharField(max_length=50, verbose_name='주소')),
                ('space', models.CharField(max_length=10, verbose_name='면적')),
                ('construction_firm', models.CharField(max_length=20, verbose_name='건설사')),
                ('low_high', models.CharField(max_length=10, verbose_name='저/고층')),
                ('household', models.PositiveSmallIntegerField(verbose_name='세대주')),
            ],
        ),
    ]
